sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull alpine:3.7

script:
  - cd hugo && docker build -t yonh/bin-hugo .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yonh/bin-hugo

#deploy:
#  provider: script
#  script: bash docker_push
#  on:
#    branch: master
